/**
 * OLIVÍCOLA LUJÁN · Catálogos y datos iniciales de demostración
 * Proporciona 12 tambores de ejemplo con trazabilidad completa,
 * movimientos e historial.
 */

export const INITIAL_CATALOGOS = [
  // Productos
  { id: 'cat-prod-1', tipo: 'producto', nombre: 'Aceituna de Mesa', codigo: 'ENT', activo: true, orden: 1 },
  { id: 'cat-prod-2', tipo: 'producto', nombre: 'Aceite de Oliva Virgen Extra', codigo: 'AOVE', activo: true, orden: 2 },
  { id: 'cat-prod-3', tipo: 'producto', nombre: 'Aceituna Descarozada', codigo: 'DES', activo: true, orden: 3 },

  // Presentaciones
  { id: 'cat-pres-1', tipo: 'presentacion', nombre: 'Verde en Salmuera', codigo: 'VDE', activo: true, orden: 1 },
  { id: 'cat-pres-2', tipo: 'presentacion', nombre: 'Negra Natural', codigo: 'NEG', activo: true, orden: 2 },
  { id: 'cat-pres-3', tipo: 'presentacion', nombre: 'En Rodajas', codigo: 'ROD', activo: true, orden: 3 },
  { id: 'cat-pres-4', tipo: 'presentacion', nombre: 'Granel Filtrado', codigo: 'GRA', activo: true, orden: 4 },

  // Variedades
  { id: 'cat-var-1', tipo: 'variedad', nombre: 'Arauco', codigo: 'ALOR', activo: true, orden: 1 },
  { id: 'cat-var-2', tipo: 'variedad', nombre: 'Manzanilla', codigo: 'MANZ', activo: true, orden: 2 },
  { id: 'cat-var-3', tipo: 'variedad', nombre: 'Picual', codigo: 'PIC', activo: true, orden: 3 },
  { id: 'cat-var-4', tipo: 'variedad', nombre: 'Changlot', codigo: 'CHA', activo: true, orden: 4 },
  { id: 'cat-var-5', tipo: 'variedad', nombre: 'Farga (Histórica)', codigo: 'FAR', activo: false, orden: 99 },

  // Calibres
  { id: 'cat-cal-1', tipo: 'calibre', nombre: '161/200', codigo: '161/200', activo: true, orden: 1 },
  { id: 'cat-cal-2', tipo: 'calibre', nombre: '201/240', codigo: '201/240', activo: true, orden: 2 },
  { id: 'cat-cal-3', tipo: 'calibre', nombre: '241/280', codigo: '241/280', activo: true, orden: 3 },
  { id: 'cat-cal-4', tipo: 'calibre', nombre: '281/320', codigo: '281/320', activo: true, orden: 4 },
  { id: 'cat-cal-5', tipo: 'calibre', nombre: 'Sin Calibrar (S/C)', codigo: 'S/C', activo: true, orden: 5 },

  // Calidades
  { id: 'cat-qual-1', tipo: 'calidad', nombre: 'Primera', codigo: 'PRI', activo: true, orden: 1 },
  { id: 'cat-qual-2', tipo: 'calidad', nombre: 'Segunda', codigo: 'SEG', activo: true, orden: 2 },
  { id: 'cat-qual-3', tipo: 'calidad', nombre: 'Exportación Premium', codigo: 'EXP', activo: true, orden: 3 },

  // Ubicaciones
  { id: 'cat-ubi-1', tipo: 'ubicacion', nombre: 'Nave A - Fila 1', codigo: 'NAV-A1', activo: true, orden: 1 },
  { id: 'cat-ubi-2', tipo: 'ubicacion', nombre: 'Nave A - Fila 2', codigo: 'NAV-A2', activo: true, orden: 2 },
  { id: 'cat-ubi-3', tipo: 'ubicacion', nombre: 'Nave A - Fila 3', codigo: 'NAV-A3', activo: true, orden: 3 },
  { id: 'cat-ubi-4', tipo: 'ubicacion', nombre: 'Nave B - Fila 1', codigo: 'NAV-B1', activo: true, orden: 4 },
  { id: 'cat-ubi-5', tipo: 'ubicacion', nombre: 'Nave B - Fila 2', codigo: 'NAV-B2', activo: true, orden: 5 },
  { id: 'cat-ubi-6', tipo: 'ubicacion', nombre: 'Patio Fermentación', codigo: 'PAT-F', activo: true, orden: 6 },
  { id: 'cat-ubi-7', tipo: 'ubicacion', nombre: 'Sector Despacho', codigo: 'DESP', activo: true, orden: 7 },
  { id: 'cat-ubi-8', tipo: 'ubicacion', nombre: 'Depósito Histórico (Inactivo)', codigo: 'DEP-HIST', activo: false, orden: 99 },

  // Estados
  { id: 'cat-est-1', tipo: 'estado', nombre: 'En fermentación', codigo: 'FERM', activo: true, orden: 1 },
  { id: 'cat-est-2', tipo: 'estado', nombre: 'En reposo', codigo: 'REPO', activo: true, orden: 2 },
  { id: 'cat-est-3', tipo: 'estado', nombre: 'En salmuera definitiva', codigo: 'SALM', activo: true, orden: 3 },
  { id: 'cat-est-4', tipo: 'estado', nombre: 'En calibrado', codigo: 'CALI', activo: true, orden: 4 },
  { id: 'cat-est-5', tipo: 'estado', nombre: 'Aprobado calidad', codigo: 'APRO', activo: true, orden: 5 },
  { id: 'cat-est-6', tipo: 'estado', nombre: 'Retenido para análisis', codigo: 'RETE', activo: true, orden: 6 },
  { id: 'cat-est-7', tipo: 'estado', nombre: 'Listo para despacho', codigo: 'LIST', activo: true, orden: 7 },

  // Tipos de Movimiento
  { id: 'cat-mov-1', tipo: 'tipo_movimiento', nombre: 'Traslado interno de nave', codigo: 'TRAS', activo: true, orden: 1 },
  { id: 'cat-mov-2', tipo: 'tipo_movimiento', nombre: 'Reubicación por fermentación', codigo: 'REUB', activo: true, orden: 2 },
  { id: 'cat-mov-3', tipo: 'tipo_movimiento', nombre: 'Control de calidad y muestreo', codigo: 'CTRL', activo: true, orden: 3 },
  { id: 'cat-mov-4', tipo: 'tipo_movimiento', nombre: 'Ingreso desde cosecha', codigo: 'INGR', activo: true, orden: 4 },
  { id: 'cat-mov-5', tipo: 'tipo_movimiento', nombre: 'Movimiento a despacho', codigo: 'DESP', activo: true, orden: 5 },
];

export const INITIAL_TAMBORES = [
  {
    id: 'tb-001',
    tambor_id: 'T000001',
    codigo_descriptivo: 'ENT-VDE-ALOR-161/200-PRI',
    codigo: 'ENT-VDE-ALOR-161/200-PRI-T000001',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-1',
    calibre: 'cat-cal-1',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-LUJ01',
    fecha_ingreso: '2026-09-01',
    fecha_elaboracion: '2026-08-30',
    peso: 220.5,
    ubicacion: 'cat-ubi-1',
    estado: 'cat-est-1',
    observaciones: 'Tambor inaugural de cosecha Arauco. Control de pH diario.',
    created_date: '2026-09-01T08:30:00Z',
  },
  {
    id: 'tb-002',
    tambor_id: 'T000002',
    codigo_descriptivo: 'ENT-VDE-ALOR-161/200-PRI',
    codigo: 'ENT-VDE-ALOR-161/200-PRI-T000002',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-1',
    calibre: 'cat-cal-1',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-LUJ01',
    fecha_ingreso: '2026-09-01',
    fecha_elaboracion: '2026-08-30',
    peso: 219.8,
    ubicacion: 'cat-ubi-1',
    estado: 'cat-est-1',
    observaciones: 'Lote homogéneo sector este de la finca.',
    created_date: '2026-09-01T08:45:00Z',
  },
  {
    id: 'tb-003',
    tambor_id: 'T000003',
    codigo_descriptivo: 'ENT-VDE-MANZ-201/240-EXP',
    codigo: 'ENT-VDE-MANZ-201/240-EXP-T000003',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-2',
    calibre: 'cat-cal-2',
    calidad: 'cat-qual-3',
    lote: 'LOTE-2026-MAN02',
    fecha_ingreso: '2026-09-03',
    fecha_elaboracion: '2026-09-02',
    peso: 215.0,
    ubicacion: 'cat-ubi-2',
    estado: 'cat-est-5',
    observaciones: 'Manzanilla de exportación. Aprobado por laboratorio.',
    created_date: '2026-09-03T10:15:00Z',
  },
  {
    id: 'tb-004',
    tambor_id: 'T000004',
    codigo_descriptivo: 'ENT-NEG-PIC-241/280-PRI',
    codigo: 'ENT-NEG-PIC-241/280-PRI-T000004',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-2',
    variedad: 'cat-var-3',
    calibre: 'cat-cal-3',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-PIC03',
    fecha_ingreso: '2026-09-05',
    fecha_elaboracion: '2026-09-04',
    peso: 222.0,
    ubicacion: 'cat-ubi-3',
    estado: 'cat-est-2',
    observaciones: 'Negra natural en reposo para estabilización osmótica.',
    created_date: '2026-09-05T09:00:00Z',
  },
  {
    id: 'tb-005',
    tambor_id: 'T000005',
    codigo_descriptivo: 'DES-ROD-MANZ-201/240-SEG',
    codigo: 'DES-ROD-MANZ-201/240-SEG-T000005',
    producto: 'cat-prod-3',
    presentacion: 'cat-pres-3',
    variedad: 'cat-var-2',
    calibre: 'cat-cal-2',
    calidad: 'cat-qual-2',
    lote: 'LOTE-2026-ROD01',
    fecha_ingreso: '2026-09-08',
    fecha_elaboracion: '2026-09-07',
    peso: 205.5,
    ubicacion: 'cat-ubi-4',
    estado: 'cat-est-3',
    observaciones: 'Descarozada y cortada en rodajas para conserva.',
    created_date: '2026-09-08T11:20:00Z',
  },
  {
    id: 'tb-006',
    tambor_id: 'T000006',
    codigo_descriptivo: 'AOVE-GRA-ALOR-S/C-EXP',
    codigo: 'AOVE-GRA-ALOR-S/C-EXP-T000006',
    producto: 'cat-prod-2',
    presentacion: 'cat-pres-4',
    variedad: 'cat-var-1',
    calibre: 'cat-cal-5',
    calidad: 'cat-qual-3',
    lote: 'LOTE-2026-AOVE01',
    fecha_ingreso: '2026-09-10',
    fecha_elaboracion: '2026-09-10',
    peso: 195.0,
    ubicacion: 'cat-ubi-5',
    estado: 'cat-est-7',
    observaciones: 'Aceite de oliva virgen extra monovarietal Arauco. Acidez 0.18%. Listo para despacho.',
    created_date: '2026-09-10T14:30:00Z',
  },
  {
    id: 'tb-007',
    tambor_id: 'T000007',
    codigo_descriptivo: 'ENT-VDE-CHA-281/320-PRI',
    codigo: 'ENT-VDE-CHA-281/320-PRI-T000007',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-4',
    calibre: 'cat-cal-4',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-CHA01',
    fecha_ingreso: '2026-09-12',
    fecha_elaboracion: '2026-09-11',
    peso: 218.4,
    ubicacion: 'cat-ubi-6',
    estado: 'cat-est-1',
    observaciones: 'Changlot en salmuera con control térmico.',
    created_date: '2026-09-12T09:10:00Z',
  },
  {
    id: 'tb-008',
    tambor_id: 'T000008',
    codigo_descriptivo: 'ENT-VDE-ALOR-201/240-PRI',
    codigo: 'ENT-VDE-ALOR-201/240-PRI-T000008',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-1',
    calibre: 'cat-cal-2',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-LUJ02',
    fecha_ingreso: '2026-09-14',
    fecha_elaboracion: '2026-09-13',
    peso: 221.0,
    ubicacion: 'cat-ubi-1',
    estado: 'cat-est-4',
    observaciones: 'Pendiente ajuste de graduación de salmuera.',
    created_date: '2026-09-14T08:00:00Z',
  },
  {
    id: 'tb-009',
    tambor_id: 'T000009',
    codigo_descriptivo: 'ENT-NEG-MANZ-241/280-PRI',
    codigo: 'ENT-NEG-MANZ-241/280-PRI-T000009',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-2',
    variedad: 'cat-var-2',
    calibre: 'cat-cal-3',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-MAN03',
    fecha_ingreso: '2026-09-16',
    fecha_elaboracion: '2026-09-15',
    peso: 216.5,
    ubicacion: 'cat-ubi-2',
    estado: 'cat-est-6',
    observaciones: 'Retenido preventivamente por muestra de textura.',
    created_date: '2026-09-16T15:45:00Z',
  },
  {
    id: 'tb-010',
    tambor_id: 'T000010',
    codigo_descriptivo: 'ENT-VDE-PIC-161/200-EXP',
    codigo: 'ENT-VDE-PIC-161/200-EXP-T000010',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-3',
    calibre: 'cat-cal-1',
    calidad: 'cat-qual-3',
    lote: 'LOTE-2026-PIC04',
    fecha_ingreso: '2026-09-18',
    fecha_elaboracion: '2026-09-17',
    peso: 224.2,
    ubicacion: 'cat-ubi-7',
    estado: 'cat-est-7',
    observaciones: 'Calibre grande calidad exportación listo para carga de contenedor.',
    created_date: '2026-09-18T10:00:00Z',
  },
  {
    id: 'tb-011',
    tambor_id: 'T000011',
    codigo_descriptivo: 'AOVE-GRA-ALOR-S/C-EXP',
    codigo: 'AOVE-GRA-ALOR-S/C-EXP-T000011',
    producto: 'cat-prod-2',
    presentacion: 'cat-pres-4',
    variedad: 'cat-var-1',
    calibre: 'cat-cal-5',
    calidad: 'cat-qual-3',
    lote: 'LOTE-2026-AOVE02',
    fecha_ingreso: '2026-09-20',
    fecha_elaboracion: '2026-09-19',
    peso: 198.5,
    ubicacion: 'cat-ubi-5',
    estado: 'cat-est-5',
    observaciones: 'Lote prensa en frío, extracción a 24°C.',
    created_date: '2026-09-20T16:15:00Z',
  },
  {
    id: 'tb-012',
    tambor_id: 'T000012',
    codigo_descriptivo: 'ENT-VDE-ALOR-161/200-PRI',
    codigo: 'ENT-VDE-ALOR-161/200-PRI-T000012',
    producto: 'cat-prod-1',
    presentacion: 'cat-pres-1',
    variedad: 'cat-var-1',
    calibre: 'cat-cal-1',
    calidad: 'cat-qual-1',
    lote: 'LOTE-2026-LUJ03',
    fecha_ingreso: '2026-09-22',
    fecha_elaboracion: '2026-09-21',
    peso: 223.0,
    ubicacion: 'cat-ubi-1',
    estado: 'cat-est-1',
    observaciones: 'Ingresado recientemente. En proceso de monitoreo.',
    created_date: '2026-09-22T08:00:00Z',
  },
];

export const INITIAL_HISTORIAL = [
  {
    id: 'hist-001',
    tambor_id: 'T000001',
    tambor_ref: 'tb-001',
    tipo: 'Creación',
    descripcion: 'Tambor creado en el sistema con peso neto 220.5 kg',
    actor: 'Operario Planta (Demo)',
    created_date: '2026-09-01T08:30:00Z',
  },
  {
    id: 'hist-002',
    tambor_id: 'T000002',
    tambor_ref: 'tb-002',
    tipo: 'Creación',
    descripcion: 'Tambor creado en el sistema con peso neto 219.8 kg',
    actor: 'Operario Planta (Demo)',
    created_date: '2026-09-01T08:45:00Z',
  },
  {
    id: 'hist-003',
    tambor_id: 'T000003',
    tambor_ref: 'tb-003',
    tipo: 'Creación',
    descripcion: 'Tambor creado en el sistema',
    actor: 'Operario Planta (Demo)',
    created_date: '2026-09-03T10:15:00Z',
  },
  {
    id: 'hist-004',
    tambor_id: 'T000003',
    tambor_ref: 'tb-003',
    tipo: 'Movimiento',
    descripcion: 'Movimiento: Control de calidad y muestreo',
    observaciones: 'Muestreo completado satisfactoriamente para exportación',
    actor: 'Jefe de Calidad',
    created_date: '2026-09-04T11:00:00Z',
  },
  {
    id: 'hist-005',
    tambor_id: 'T000006',
    tambor_ref: 'tb-006',
    tipo: 'Movimiento',
    descripcion: 'Movimiento: Movimiento a despacho',
    observaciones: 'Trasladado a Nave B para preparación de pallet',
    actor: 'Operario Planta (Demo)',
    created_date: '2026-09-22T14:00:00Z',
  },
  {
    id: 'hist-006',
    tambor_id: 'T000010',
    tambor_ref: 'tb-010',
    tipo: 'Movimiento',
    descripcion: 'Movimiento: Movimiento a despacho',
    observaciones: 'Asignado a muelle de carga internacional',
    actor: 'Operario Planta (Demo)',
    created_date: '2026-09-23T09:30:00Z',
  },
];

export const INITIAL_MOVIMIENTOS = [
  {
    id: 'mov-rec-001',
    tambor_id: 'T000003',
    tambor_ref: 'tb-003',
    tipo: 'cat-mov-3',
    ubicacion_anterior: 'cat-ubi-1',
    ubicacion_nueva: 'cat-ubi-2',
    estado_anterior: 'cat-est-1',
    estado_nuevo: 'cat-est-5',
    observaciones: 'Aprobado tras análisis fisicoquímico.',
    created_date: '2026-09-04T11:00:00Z',
  },
  {
    id: 'mov-rec-002',
    tambor_id: 'T000006',
    tambor_ref: 'tb-006',
    tipo: 'cat-mov-5',
    ubicacion_anterior: 'cat-ubi-4',
    ubicacion_nueva: 'cat-ubi-5',
    estado_anterior: 'cat-est-5',
    estado_nuevo: 'cat-est-7',
    observaciones: 'Traslado a nave de guarda final.',
    created_date: '2026-09-22T14:00:00Z',
  },
];
